# Generated by Django 3.2.9 on 2021-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
