# Generated by Django 3.2.9 on 2021-12-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs_song_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('song_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
